# Netlify configuration for static Angular app
[build]
  command = "ng build --configuration production"
  publish = "dist/brochure/browser"

# SPA redirect for Angular routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
