[build]
  command = "npm run build"
  publish = "dist/brochure"

[functions]
  external_node_modules = ["@angular/ssr", "@netlify/angular-runtime"]

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200
