[build]
  command = "npm install && ng build --configuration=production"
  publish = "dist/brochure/browser"
  
[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--production=false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
